export default 
    {
        LOGIN:{
            path:'/user/login',
            auth:false
        },
        CREATE_USER:{
            path:'/user/create',
            auth:false
        },
        UPCOMMING:{
            path:'/program/upcoming'
        },
        VIWETOUR:{
            path:'/program/view-tour/:tourId'
        },
        CREATE_PROGRAM:{
            path:'/program/create-program',
            auth:true
        },
        GET_ALLUSERS:{
            path:'/user/all-users',
            auth:true
        },
        GET_ALL_BOOKINGS:{
            path:'/tour/booked-status',
            auth:true
        },
        CREATE_BOOKING:{
            path:'/tour/booking',
            auth:true
        },
        USER_BOOKEND_STATUS:{
            path:'/user/user-booked-status',
            auth:true
        },
    }
